eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8082
  max-http-header-size: 10485760
spring:
  application:
    name: service-feign
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
  data:
    redis: #redis缓存
      database: 0
      host: localhost
      port: 6379
      password:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

ribbon:
  eureka:
    enabled: true
