server:
  port: 8081
  max-http-header-size: 1048576

spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enable: true
  application:
    name: service-provider
  datasource: #mysql数据库
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:://192.168.1.12 1/zhaopin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis: #mybatis映射文件
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2